### ISSUE TITLE
Connectors plugin cannot mate connectors by default on simulation start.

### ISSUE THREAD

**Issue by georgeslabreche** [rock-simulation/mars#105]
Given the following YAML with `mating: automatic` for both male and female connectors:

```yaml
    connectors:
        types:
        - name: transterra
          distance: 0.15
          angle: 3.1415
          maxforce: 100

        connectors:
        - gender: male
          link: male_connector
          mating: automatic
          name: payload_male_connector
          type: transterra
        - gender: female
          link: female_connector
          mating: automatic
          name: payload_female_connector
          type: transterra
```

## Connectors mating property
When the connector's mating properties are set to automatic, I would expect male and female connectors to automatically mate regardless of what the plugin's autoconnect property is set to. If not, then what is the point of the mating properties, particularly when set to automatic?

Currently, mating properties are not interpreted by the plugin in any fashion.

## Default autoconnect plugin property
The default value for autoconnect plugin property is hardcoded in the connector's init() method. Would be good to externalize setting this property in the case of connections that need to connect on simulation start.

Proposed exteranilization into the YAML:

```yaml
   autoconnect: true
    connectors:
        types:
        - name: transterra
          distance: 0.15
          angle: 3.1415
          maxforce: 100

        connectors:
        - gender: male
          link: male_connector
          mating: automatic
          name: payload_male_connector
          type: transterra
        - gender: female
          link: female_connector
          mating: automatic
          name: payload_female_connector
          type: transterra
```

## Connectors plugin not loaded by default
For cases where connections need to happen on simulation start, we need to fetch, install, and load the Connectors plugin by default. See MARS::loadAdditionalLibs().

## WIP merge request
 [Proposed fix](https://github.com/rock-simulation/mars/pull/106).
